DISCORD:
  BOT_TOKEN: ""
  CHANNEL_ID: ""
  UPDATE_MESSAGE_ID: 0
  Port: "25565"
  UPDATE_MESSAGE: ":arrow_down: :arrow_down: :arrow_down: __**Server IP**__ :arrow_down: :arrow_down: :arrow_down:\n# **%server_ip%:%port%**\n (last updated: %currentdatetime% *server's local time*)"
