name: Minecraft_Simple_IP_Bot
version: '${project.version}'
main: Minecraft_Simple_IP_Bot.Minecraft_Simple_IP_Bot
api-version: 1.19
folia-supported: true
load: STARTUP
libraries:
  - net.dv8tion:JDA:5.0.0-beta.18
